from fastapi import status

OK = status.HTTP_200_OK
CREATED = status.HTTP_202_ACCEPTED
NOT_MODIFIED = status.HTTP_304_NOT_MODIFIED
NOT_FOUND = status.HTTP_404_NOT_FOUND
BAD_REQUEST = status.HTTP_400_BAD_REQUEST
UNAUTHORIZED = status.HTTP_401_UNAUTHORIZED
FORBIDDEN = status.HTTP_403_FORBIDDEN
NOT_ACEPTABLE = status.HTTP_406_NOT_ACCEPTABLE
